version: '2.1'

services:
    mavros-avoidance:
        extends:
            file: ../../components/components.yml
            service: mavros-avoidance
    sitl-avoidance-server:
        extends:
            file: ../../components/components.yml
            service: sitl-avoidance-server
        depends_on:
            - mavros-avoidance
    sitl-avoidance-gui:
        extends:
            file: ../../components/components.yml
            service: sitl-avoidance-gui
        depends_on:
            - sitl-avoidance-server
        command: /root/avoidance/resource/local_planning.rviz
    avoidance-node:
        extends:
            file: ../../components/components.yml
            service: avoidance-node
        depends_on:
            - sitl-avoidance-server
        command: local_avoidance.launch use_sim_time:="true"
